### ISSUE TITLE
리드미의 몰래 사용에 대한 당부에 관하여

### ISSUE THREAD

**Issue by noamboy2006** [noryonkr/noryon-bot#2]
라이센스를 추가하는건 어떨까요

**Comment by noryonkr** [comment]
생각해보고 추가해보겠습니다!
![1592993890383](https://user-images.githubusercontent.com/63511753/85752274-3d2a5680-b746-11ea-80e9-fcf13c7b1212.png)

**Comment by noryonkr** [comment]
전에 닫아놨어야 하는건데 안닫음 ㅎㅎ;;
